name: trustlaundry
description: "The trust laundry mobile application"
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies: # some dependecies
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  mailer: ^6.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  location: 6.0.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  go_sell_sdk_flutter: ^2.4.10
  pdf: ^3.11.1
  flutter_animate: ^4.5.0
  share_plus: ^10.1.2
  skeletonizer: ^2.1.0+1
  flutter_tap_payment: ^0.2.1
  flutter_social_button: ^1.1.4+1
  widget_and_text_animator: ^1.1.5
  webview_flutter: ^4.8.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  assets:
    - assets/images/
    - assets/vectors/
    - assets/animations/
    - assets/fonts/
  uses-material-design: true